name: build

on:
  pull_request:
  workflow_call:

permissions:
  contents: read

jobs:
  build-cicd-app:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5
      - name: Setup Node.js
        uses: actions/setup-node@2028fbc5c25fe9cf00d9f06a71cc4710d4507903 # v6
        with:
          node-version: 22.x
      - name: Install CDK dependencies
        run: npm ci
      - name: Build cloud assembly
        run: npx cdk synth --app "npx ts-node --prefer-ts-exts bin/cicd.ts"
      - name: Upload artifact
        uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4
        with:
          name: cicd-app-cloud-assembly
          path: cdk.out
  build-dns-app:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5
      - name: Setup Node.js
        uses: actions/setup-node@2028fbc5c25fe9cf00d9f06a71cc4710d4507903 # v6
        with:
          node-version: 22.x
      - name: Install CDK dependencies
        run: npm ci
      - name: Build cloud assembly
        run: npx cdk synth --app "npx ts-node --prefer-ts-exts bin/dns.ts"
      - name: Upload artifact
        uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4
        with:
          name: dns-app-cloud-assembly
          path: cdk.out
  build-domain-placeholder-app:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5
      - name: Setup Node.js
        uses: actions/setup-node@2028fbc5c25fe9cf00d9f06a71cc4710d4507903 # v6
        with:
          node-version: 22.x
      - name: Install CDK dependencies
        run: npm ci
      - name: Build cloud assembly
        run: npx cdk synth --app "npx ts-node --prefer-ts-exts bin/domain-placeholder.ts"
      - name: Upload artifact
        uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4
        with:
          name: domain-placeholder-app-cloud-assembly
          path: cdk.out
  build-log-redirect-app:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5
      - name: Setup Node.js
        uses: actions/setup-node@2028fbc5c25fe9cf00d9f06a71cc4710d4507903 # v6
        with:
          node-version: 22.x
      - name: Install CDK dependencies
        run: npm ci
      - name: Install Lambda dependencies
        working-directory: ./lambda/log-redirect
        run: npm ci
      - name: Install frontend dependencies
        working-directory: ./frontend/log-redirect
        run: npm ci
      - name: Build frontend
        working-directory: ./frontend/log-redirect
        run: npm run build
      - name: Build cloud assembly
        run: npx cdk synth --app "npx ts-node --prefer-ts-exts bin/log-redirect.ts"
      - name: Upload artifact
        uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4
        with:
          name: log-redirect-app-cloud-assembly
          path: cdk.out
  build-prime-scout-app:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5
      - name: Setup Node.js
        uses: actions/setup-node@2028fbc5c25fe9cf00d9f06a71cc4710d4507903 # v6
        with:
          node-version: 22.x
      - name: Install CDK dependencies
        run: npm ci
      - name: Install Lambda dependencies
        working-directory: ./lambda/prime-scout
        run: npm ci
      - name: Install frontend dependencies
        working-directory: ./frontend/prime-scout
        run: npm ci
      - name: Build frontend
        working-directory: ./frontend/prime-scout
        run: npm run build
      - name: Build cloud assembly
        run: npx cdk synth --app "npx ts-node --prefer-ts-exts bin/prime-scout.ts"
      - name: Upload artifact
        uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4
        with:
          name: prime-scout-app-cloud-assembly
          path: cdk.out
  build-character-list-app:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5
      - name: Setup Node.js
        uses: actions/setup-node@2028fbc5c25fe9cf00d9f06a71cc4710d4507903 # v6
        with:
          node-version: 22.x
      - name: Install CDK dependencies
        run: npm ci
      - name: Install Lambda dependencies
        working-directory: ./lambda/character-list
        run: npm ci
      - name: Install frontend dependencies
        working-directory: ./frontend/character-list
        run: npm ci
      - name: Build frontend
        working-directory: ./frontend/character-list
        run: npm run build
      - name: Build cloud assembly
        run: npx cdk synth --app "npx ts-node --prefer-ts-exts bin/character-list.ts"
      - name: Upload artifact
        uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4
        with:
          name: character-list-app-cloud-assembly
          path: cdk.out
  build-home-assistant-app:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5
      - name: Setup Node.js
        uses: actions/setup-node@2028fbc5c25fe9cf00d9f06a71cc4710d4507903 # v6
        with:
          node-version: 22.x
      - name: Install CDK dependencies
        run: npm ci
      - name: Build cloud assembly
        run: npx cdk synth --app "npx ts-node --prefer-ts-exts bin/home-assistant.ts"
      - name: Upload artifact
        uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4
        with:
          name: home-assistant-app-cloud-assembly
          path: cdk.out